<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>proj</string>
		<string>targets</string>
		<string>msbuild</string>
		<string>csproj</string>
		<string>vbproj</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>name</key>
	<string>MSBuild</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)\s*([-_a-zA-Z0-9]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Preprocessor directives</string>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>name</key>
			<string>meta.tag.preprocessor.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string> ([a-zA-Z-]+)</string>
					<key>name</key>
					<string>entity.other.attribute-name.msbuild</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doubleQuotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleQuotedString</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comment blocks</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>comment.block.msbuild</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(ItemGroup|Import|Output|ParameterGroup|Project|ProjectExtensions|PropertyGroup|Target|UsingTask)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.source.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MSBuild keywords</string>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagAttribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(Choose|OnError|Otherwise|When)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MSBuild flow control</string>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagAttribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(AL|AspNetCompiler|AssignCulture|AssignProjectConfiguration|AssignTargetPath|CallTarget|CombinePath|ConvertToAbsolutePath|Copy|CreateCSharpManifestResourceName|CreateItem|CreateProperty|CreateVisualBasicManifestResourceName|Csc|Delete|Error|Exec|FindAppConfigFile|FindInList|FindUnderPath|FormatUrl|FormatVersion|GenerateApplicationManifest|GenerateDeploymentManifest|GenerateResource|GenerateTrustInfo|GetAssemblyIdentity|GetFrameworkPath|GetFrameworkSdkPath|GetReferenceAssemblyPaths|LC|MakeDir|Message|Move|MSBuild|ReadLinesFromFile|RegisterAssembly|RemoveDir|RemoveDuplicates|RequiresFramework35SP1Assembly|ResolveAssemblyReference|ResolveComReference|ResolveKeySource|ResolveManifestFiles|ResolveNativeReference|REsolveNonMSBuildProjectOutput|SGen|SignFile|Touch|UnregisterAssembly|UpdateManifest|Vbc|Warning|WriteCodeFragment|WriteLinesToFile|XmlPeek|XmlPoke|XslTransformation)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.source.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MSBuild tasks</string>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagAttribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(CodeAnalysisDictionary|Compile|Content|EmbeddedResource|None|Reference)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.source.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Project item types</string>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagAttribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9:]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.msbuild</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.msbuild</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.msbuild</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Standard tags</string>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagAttribute</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Allow encoded entities</string>
			<key>include</key>
			<string>#entity</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>No floating unencoded ampersands</string>
			<key>include</key>
			<string>#bareAmpersand</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Well-known variables in tag inner text</string>
			<key>include</key>
			<string>#reservedProperty</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Well-known item metadata embedded in variables</string>
			<key>include</key>
			<string>#wellKnownMetadataEmbedded</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Item references in tag inner text</string>
			<key>include</key>
			<string>#itemReference</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables in tag inner text</string>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!\[CDATA\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>CDATA sections</string>
			<key>end</key>
			<string>]]&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.cdata.msbuild</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bareAmpersand</key>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>invalid.illegal.bad-ampersand.msbuild</string>
		</dict>
		<key>doubleQuotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.msbuild</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#reservedProperty</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#itemReference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#predicate</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareAmpersand</string>
				</dict>
			</array>
		</dict>
		<key>entity</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.msbuild</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.msbuild</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&amp;)([:a-zA-Z_][:a-zA-Z0-9_.-]*|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
			<key>name</key>
			<string>constant.character.entity.msbuild</string>
		</dict>
		<key>itemReference</key>
		<dict>
			<key>begin</key>
			<string>\%\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>%(Foo.Bar) or %(Metadata) references - separate so well-known metadata will only highlight in these variables</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter.item.source.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wellKnownMetadataInline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareAmpersand</string>
				</dict>
			</array>
		</dict>
		<key>nestedParens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Handles nested parentheses in a property.</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter.property.source.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wellKnownMetadataEmbedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#itemReference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareAmpersand</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(==|!=?|&amp;gt;=?|&amp;lt;=?|\bAnd\b|\bOr\b)</string>
			<key>name</key>
			<string>keyword.operator.source.msbuild</string>
		</dict>
		<key>predicate</key>
		<dict>
			<key>begin</key>
			<string>\b(Exists|HasTrailingSlash)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.source.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameter-list.begin.msbuild</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameter-list.end.msbuild</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleQuotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doubleQuotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareAmpersand</string>
				</dict>
			</array>
		</dict>
		<key>reservedProperty</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.source.msbuild</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Properties provided by MSBuild</string>
			<key>match</key>
			<string>(?i)(\$\()(MSBuild(BinPath|ExtensionsPath(?:32|64)?|ProjectDefaultTargets|ProjectDirectory|ProjectExtension|ProjectFile|ProjectFullPath|ProjectName|StartupDirectory))(\))</string>
			<key>name</key>
			<string>support.constant.source.msbuild</string>
		</dict>
		<key>singleQuotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.msbuild</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#reservedProperty</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#itemReference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#predicate</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareAmpersand</string>
				</dict>
			</array>
		</dict>
		<key>tagAttribute</key>
		<dict>
			<key>comment</key>
			<string>SomeAttribute=SomeValue</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.namespace.msbuild</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.msbuild</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.msbuild</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.localname.msbuild</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s+(?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9]+)\s*=\s*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doubleQuotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleQuotedString</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>begin</key>
			<string>(?:\$|\@)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variables that are properties or lists, not item references</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end.msbuild</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter.property.source.msbuild</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reservedProperty</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wellKnownMetadataEmbedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#itemReference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedParens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bareAmpersand</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>keyword.operator.source.msbuild</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)Registry:</string>
					<key>name</key>
					<string>support.function.source.msbuild</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Inline framework static class functions supported</string>
					<key>match</key>
					<string>\[(?:(?:Microsoft\.Build\.Utilities\.ToolLocationHelper)|(?:System\.(?:Byte|Char|Convert|DateTime|Decimal|Double|Enum|Environment|Guid|U?Int(?:16|32|64)|IO\.(?:Directory|File|Path)|Math|SByte|Single|String(?:Comparer)?|TimeSpan|Text\.RegularExpressions\.Regex)))\]::[_a-zA-Z0-9]+</string>
					<key>name</key>
					<string>support.function.source.msbuild</string>
				</dict>
			</array>
		</dict>
		<key>wellKnownMetadataEmbedded</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.msbuild</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Well-known metadata like @(VarName -&gt; %(Metadata))</string>
			<key>match</key>
			<string>(\%\()(?:AccessedTime|CreatedTime|Directory|Extension|Filename|FullPath|Identity|ModifiedTime|RecursiveDir|RelativeDir|RootDir)(\))</string>
			<key>name</key>
			<string>support.constant.source.msbuild</string>
		</dict>
		<key>wellKnownMetadataInline</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.dot-access.msbuild</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Well-known metadata like %(ItemName.Metadata)</string>
			<key>match</key>
			<string>(\.)(?:AccessedTime|CreatedTime|Directory|Extension|Filename|FullPath|Identity|ModifiedTime|RecursiveDir|RelativeDir|RootDir)\b</string>
			<key>name</key>
			<string>support.constant.source.msbuild</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.msbuild</string>
	<key>uuid</key>
	<string>03ca5980-703e-4ee9-8271-d34088df8532</string>
</dict>
</plist>
